/**
 * GENERATED by tools/boss_mounts.py from the cyan markers on the boss body
 * sprites. Offsets are sprite pixels from the body's bottom-centre, right-facing.
 * Do not edit by hand; regenerate after replacing a boss sheet.
 */
export interface BossMounts {
  width: number;
  height: number;
  mounts: { dx: number; dy: number }[];
}

export const BOSS_MOUNTS: Record<string, BossMounts> = {
  'behemoth': {
    'width': 311,
    'height': 153,
    'mounts': [
      {
        'dx': -83,
        'dy': -60
      },
      {
        'dx': -43,
        'dy': -106
      },
      {
        'dx': 66,
        'dy': -106
      },
      {
        'dx': 80,
        'dy': -60
      }
    ]
  },
  'juggernaut': {
    'width': 331,
    'height': 158,
    'mounts': [
      {
        'dx': -94,
        'dy': -64
      },
      {
        'dx': -59,
        'dy': -106
      },
      {
        'dx': 78,
        'dy': -64
      }
    ]
  },
  'hive': {
    'width': 355,
    'height': 157,
    'mounts': [
      {
        'dx': -40,
        'dy': -84
      },
      {
        'dx': 16,
        'dy': -119
      },
      {
        'dx': 92,
        'dy': -83
      }
    ]
  }
};
