"""
Read the cyan (#00FFFF) mount markers off each boss body sprite and write
src/core/campaign/mounts.ts, so hardpoint positions match the art exactly.

    py -3 tools/boss_mounts.py

Offsets are in sprite pixels relative to the body's bottom-centre, for the
right-facing sprite as drawn. The game mirrors them when the boss faces left.
"""
from __future__ import annotations

import json
from collections import deque
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ATLAS = ROOT / "public" / "atlas"
OUT = ROOT / "src" / "core" / "campaign" / "mounts.ts"


def cyan_blobs(img: Image.Image) -> list[tuple[float, float]]:
    a = np.asarray(img.convert("RGBA")).astype(int)
    r, g, b, al = a[..., 0], a[..., 1], a[..., 2], a[..., 3]
    mask = (al > 100) & (g > 170) & (b > 170) & (r < 120)
    h, w = mask.shape
    seen = np.zeros_like(mask)
    out = []
    ys, xs = np.nonzero(mask)
    for sy, sx in zip(ys, xs):
        if seen[sy, sx]:
            continue
        q = deque([(sy, sx)])
        seen[sy, sx] = True
        pts = []
        while q:
            y, x = q.popleft()
            pts.append((x, y))
            for ny, nx in ((y - 1, x), (y + 1, x), (y, x - 1), (y, x + 1)):
                if 0 <= ny < h and 0 <= nx < w and mask[ny, nx] and not seen[ny, nx]:
                    seen[ny, nx] = True
                    q.append((ny, nx))
        if len(pts) >= 4:
            out.append((sum(p[0] for p in pts) / len(pts), sum(p[1] for p in pts) / len(pts)))
    return out


def main() -> None:
    result: dict[str, dict] = {}
    for boss in ("behemoth", "juggernaut", "hive"):
        d = ATLAS / f"boss-{boss}"
        names = json.loads((d / "names.json").read_text())
        body_idx = next(k for k, v in names.items() if v == f"boss.{boss}.body")
        sheet = json.loads((d / "sheet.json").read_text())
        entry = next(e for e in sheet["sprites"] if f"{e['index']:02d}" == body_idx)
        w, h = entry["size"]
        mounts = entry.get("mounts")
        if not mounts:  # fall back to scanning the sprite (pre-inpaint extraction)
            pts = sorted(cyan_blobs(Image.open(d / f"{body_idx}.png")), key=lambda p: p[0])
            mounts = [{"dx": round(x - w / 2), "dy": round(y - h)} for x, y in pts]
        result[boss] = {"width": w, "height": h, "mounts": mounts}
        print(f"{boss}: {w}x{h}, {len(mounts)} mounts -> {mounts}")

    lines = [
        "/**",
        " * GENERATED by tools/boss_mounts.py from the cyan markers on the boss body",
        " * sprites. Offsets are sprite pixels from the body's bottom-centre, right-facing.",
        " * Do not edit by hand; regenerate after replacing a boss sheet.",
        " */",
        "export interface BossMounts {",
        "  width: number;",
        "  height: number;",
        "  mounts: { dx: number; dy: number }[];",
        "}",
        "",
        "export const BOSS_MOUNTS: Record<string, BossMounts> = " + json.dumps(result, indent=2).replace('"', "'") + ";",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf8")
    print("wrote", OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
