"""
Find the route nodes (plain white circles) on assets/raw/campaign-map.png and write
src/core/campaign/mapNodes.ts with their positions as fractions of the image size,
ordered along the route from the start (bottom-left) by nearest-neighbour chaining.

    py -3 tools/map_nodes.py
"""
from __future__ import annotations

import json
from collections import deque
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "assets" / "raw" / "campaign-map.png"
OUT = ROOT / "src" / "core" / "campaign" / "mapNodes.ts"


def main() -> None:
    img = Image.open(SRC).convert("RGB")
    a = np.asarray(img).astype(int)
    r, g, b = a[..., 0], a[..., 1], a[..., 2]
    # Node discs are the brightest, most neutral things on the map.
    mask = (r > 225) & (g > 225) & (b > 225) & (np.abs(r - b) < 20)
    h, w = mask.shape
    seen = np.zeros_like(mask)
    nodes = []
    ys, xs = np.nonzero(mask)
    for sy, sx in zip(ys, xs):
        if seen[sy, sx]:
            continue
        q = deque([(sy, sx)])
        seen[sy, sx] = True
        pts = []
        while q:
            y, x = q.popleft()
            pts.append((x, y))
            for ny, nx in ((y - 1, x), (y + 1, x), (y, x - 1), (y, x + 1)):
                if 0 <= ny < h and 0 <= nx < w and mask[ny, nx] and not seen[ny, nx]:
                    seen[ny, nx] = True
                    q.append((ny, nx))
        n = len(pts)
        if n < 150:
            continue
        xs_ = [p[0] for p in pts]
        ys_ = [p[1] for p in pts]
        bw, bh = max(xs_) - min(xs_) + 1, max(ys_) - min(ys_) + 1
        # Roughly circular and roughly filled: a disc, not a salt flat or a bone.
        if bw > 60 or bh > 60 or abs(bw - bh) > max(bw, bh) * 0.35:
            continue
        if n < 0.5 * bw * bh:
            continue
        nodes.append((sum(xs_) / n, sum(ys_) / n))

    # Chain from the node nearest the bottom-left corner.
    order = []
    rest = nodes[:]
    cur = min(rest, key=lambda p: (p[0] / w) ** 2 + (1 - p[1] / h) ** 2)
    while rest:
        rest.remove(cur)
        order.append(cur)
        if not rest:
            break
        cur = min(rest, key=lambda p: (p[0] - cur[0]) ** 2 + (p[1] - cur[1]) ** 2)

    data = [{"x": round(x / w, 4), "y": round(y / h, 4)} for x, y in order]
    print(f"{len(data)} nodes")
    OUT.write_text(
        "/**\n * GENERATED by tools/map_nodes.py from the white route markers on campaign-map.png.\n"
        " * Fractions of the image size, in route order. Regenerate after replacing the map.\n */\n"
        "export const MAP_NODES: { x: number; y: number }[] = " + json.dumps(data).replace('"', "") + ";\n",
        encoding="utf8",
    )
    print("wrote", OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
